apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqyards-api
  name: sqyards-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqyards-api
  template:
    metadata:
      labels:
        app: sqyards-api
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/zelarsoft-350108/sqyards/api-image:v1
        name: sq-api
        ports:
          - containerPort: 8081
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
        - name: api-config
          mountPath: /docker/config
      volumes:
      - name: api-config
        configMap:
          name: api-conf
