apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqyards-fe
  name: sqyards-fe
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sqyards-fe
  template:
    metadata:
      labels:
        app: sqyards-fe
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/zelarsoft-350108/sqyards/front-end-image:v1
        name: sq-fe
        ports:
          - containerPort: 8888
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

